name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true
      - run: go build -v ./...
      - run: go test -v -race -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./...
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true
      - uses: golangci/golangci-lint-action@v3

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true
      - uses: goreleaser/goreleaser-action@v3
        with:
          args: release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        with:
          images: ghcr.io/alicenet/json-rpc-proxy
      - uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:cmd/json-rpc-proxy"
          push: false
          tags: json-rpc-proxy:latest
