name: project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
env:
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: srggrs/assign-one-project-github-action@1.3.1
        with:
          project: "https://github.com/orgs/alicenet/projects/4"
